# This docker-compose file is only for local development purposes.
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - FILE_BUCKET_NAME
    volumes:
      - './init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh' # Initialise the bucket.
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: askgov
      POSTGRES_PASSWORD: password
      POSTGRES_DB: askgov_dev
    ports:
      - "5432:5432"
    volumes:
      - askgov_data:/var/lib/postgresql/data

volumes:
  askgov_data: